version: "3.8"

services:
  backend:
    build:
      context: ./polling-site-backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        JWT_SECRET: ${JWT_SECRET}
    image: pollingsite-be-image
    container_name: pollingsite-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./polling-site-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://0.0.0.0:3001
    image: pollingsite-fe-image
    container_name: pollingsite-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://0.0.0.0:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
